create table if not exists country
(
    id        bigint generated by default as identity
    primary key,
    continent varchar(255),
    name      varchar(255)
    );

alter table country
    owner to emt;

create table if not exists host
(
    id         bigint generated by default as identity
    primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint
    constraint "FK2g83copq8rn9b4pkqlkc2vnbo"
    references country
    );

alter table host
    owner to emt;

create table if not exists accommodation
(
    id        bigint generated by default as identity
    primary key,
    category  varchar(255)
    constraint accommodation_category_check
    check ((category)::text = ANY
((ARRAY ['ROOM'::character varying, 'HOUSE'::character varying, 'FLAT'::character varying, 'APARTMENT'::character varying, 'HOTEL'::character varying, 'MOTEL'::character varying])::text[])),
    is_rented boolean not null,
    name      varchar(255),
    num_rooms integer,
    host_id   bigint
    constraint "FK12jj342mjfhb4qx2sapi5x8xj"
    references host
    );

alter table accommodation
    owner to emt;

create table if not exists hotel_users
(
    username                   varchar(255) not null
    primary key,
    is_account_non_expired     boolean      not null,
    is_account_non_locked      boolean      not null,
    is_credentials_non_expired boolean      not null,
    is_enabled                 boolean      not null,
    name                       varchar(255),
    password                   varchar(255),
    role                       varchar(255)
    constraint hotel_users_role_check
    check ((role)::text = ANY
((ARRAY ['ROLE_USER'::character varying, 'ROLE_HOST'::character varying])::text[])),
    surname                    varchar(255)
    );

alter table hotel_users
    owner to emt;

create table if not exists temporary_reservation_list
(
    id                    bigint generated by default as identity
    primary key,
    temporary_list_status varchar(255)
    constraint temporary_reservation_list_temporary_list_status_check
    check ((temporary_list_status)::text = ANY
((ARRAY ['CREATED'::character varying, 'CANCELED'::character varying, 'FINISHED'::character varying])::text[])),
    user_username         varchar(255)
    constraint "FK35idrsxr1eppq2h3u61o5c421"
    references hotel_users
    );

alter table temporary_reservation_list
    owner to emt;

create table if not exists temporary_reservation_list_accommodations
(
    temporary_reservation_list_id bigint not null
    constraint "FKhhr286se6dar7a53oskdbqyo3"
    references temporary_reservation_list,
    accommodations_id             bigint not null
    constraint "FKfga31v1dahix3r9join74qqll"
    references accommodation
);

alter table temporary_reservation_list_accommodations
    owner to emt;

